### ISSUE TITLE
PWA not installable 

### ISSUE THREAD

**Issue by zhuoyang** [penguin-statistics/frontend-v2#332] opened 2020-05-25 18:24 UTC
### Environment
`Mozilla/5.0 (Linux; Android 10; ONEPLUS A6000) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Mobile Safari/537.36`

### URL
`https://penguin-stats.io`

### Steps to reproduce
1. Go to the website 
2. Press add to home screen 

### What is expected?
Website can be installed, install prompt will pop up on bottom of the site. Add to home screen working 

### What is actually happening?
Website cannot be installed , no install prompt popup on bottom of the site, add to home screen not working (app not showing up)

---
Tested with Twitter website, can confirm Twitter is installable

**Comment by GalvinGao** [comment] 2020-05-25 18:25
This is very weird... Because we are using the _EXACT SAME_ Chrome versions.
Can you please try to see if the PWA is installable through the menu item `Add to Homescreen`?

**Comment by zhuoyang** [comment] 2020-05-25 18:32
https://imgur.com/eEUthve
this is what happened if I press Add to Homescreen
it just appeared as a normal browser bookmark

**Comment by zhuoyang** [comment] 2020-05-25 18:42
more info, it doesn't seems to be installable on windows chrome too

![image](https://user-images.githubusercontent.com/1240039/82836879-1506c800-9efa-11ea-9eef-0b295c1fa0e2.png)
![image](https://user-images.githubusercontent.com/1240039/82836936-441d3980-9efa-11ea-8e40-b96f0430e49a.png)

this could be the problem, not quite sure about it
![image](https://user-images.githubusercontent.com/1240039/82837005-73cc4180-9efa-11ea-877e-517e79f09f92.png)

**Comment by GalvinGao** [comment] 2020-05-25 18:55
Issue has been reproduced and identified: this is because ServiceWorker is missing a `fetch` handling event.
Fixed in d0c709d2365d02f35a0dea3714e6280612ab3e20, will be in effect when release `3.1.1` being published.

Thanks for reporting this issue! ;)

**Comment by zhuoyang** [comment] 2020-05-25 19:06
great, that's quick!

**Closed** 2020-07-05 06:07 UTC
Labels: affect:ui, bug, priority:2
