### ISSUE TITLE
US SERVER ARKPLANER SHOWING STAGE 6 FORM CN SERVER

### ISSUE THREAD

**Issue by statting** [penguin-statistics/frontend-v2#340] opened 2020-06-26 09:40 UTC
<details>
<summary>Planner Config</summary>

[{"id":"30135","name":"D32钢","need":4,"have":6},{"id":"30125","name":"双极纳米片","need":0,"have":0},{"id":"30115","name":"聚合剂","need":0,"have":1},{"id":"30074","name":"白马醇","need":6,"have":12},{"id":"30073","name":"扭转醇","need":0,"have":0},{"id":"30084","name":"三水锰矿","need":8,"have":0},{"id":"30083","name":"轻锰矿","need":0,"have":57},{"id":"30094","name":"五水研磨石","need":0,"have":2},{"id":"30093","name":"研磨石","need":0,"have":1},{"id":"30104","name":"RMA70-24","need":0,"have":0},{"id":"30103","name":"RMA70-12","need":0,"have":13},{"id":"30014","name":"提纯源岩","need":0,"have":0},{"id":"30013","name":"固源岩组","need":0,"have":0},{"id":"30012","name":"固源岩","need":0,"have":4},{"id":"30011","name":"源岩","need":0,"have":0},{"id":"30064","name":"改量装置","need":5,"have":0},{"id":"30063","name":"全新装置","need":8,"have":1},{"id":"30062","name":"装置","need":0,"have":1},{"id":"30061","name":"破损装置","need":0,"have":3},{"id":"30034","name":"聚酸酯块","need":0,"have":4},{"id":"30033","name":"聚酸酯组","need":0,"have":17},{"id":"30032","name":"聚酸酯","need":0,"have":0},{"id":"30031","name":"酯原料","need":0,"have":0},{"id":"30024","name":"糖聚块","need":0,"have":4},{"id":"30023","name":"糖组","need":17,"have":72},{"id":"30022","name":"糖","need":0,"have":12},{"id":"30021","name":"代糖","need":0,"have":15},{"id":"30044","name":"异铁块","need":0,"have":13},{"id":"30043","name":"异铁组","need":0,"have":2},{"id":"30042","name":"异铁","need":0,"have":0},{"id":"30041","name":"异铁碎片","need":0,"have":1},{"id":"30054","name":"酮阵列","need":0,"have":12},{"id":"30053","name":"酮凝集组","need":0,"have":0},{"id":"30052","name":"酮凝集","need":0,"have":7},{"id":"30051","name":"双酮","need":0,"have":4}]

</details>

it goes stage 6 on it

**Comment by GalvinGao** [comment] 2020-06-28 01:39
Thanks for reporting this issue. After we've done refactoring Planner this shall be fixed.

**Comment by GalvinGao** [comment] 2020-06-28 01:41
Duplicate of #337, closing
We will be releasing the fix for Planner in the upcoming days ;)

**Closed by GalvinGao** 2020-06-28 01:41 UTC
Labels: affect:logic, affect:ui, bug, priority:0
