### ISSUE TITLE
Make item name clickable

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/frontend-v2#7] opened 2019-08-07 05:33 UTC
### What problem does this feature solve?
On result page (by item), can we also make item names clickable? It is good to show a small arrow when user moves the cursor above item names like what you design on result page (by stage).

### What does the proposed API look like?
N/A

**Comment by GalvinGao** [comment] 2019-08-07 16:26
Duplicate of #4

**Closed by GalvinGao** 2019-08-07 16:26 UTC
Labels: feature request
